### ISSUE TITLE
Can the author provide some other datasets?

### ISSUE THREAD

**Issue by sseij** [tomoyoshki/focal#1]

**Comment by tomoyoshki** [comment]
Hi there,

In addition to MOD, we evaluated FOCAL on two other open-source datasets: PAMAP2 and RealWorld-HAR.

PAMAP2: [PAMAP2 Physical Activity Monitoring](https://archive.ics.uci.edu/dataset/231/pamap2+physical+activity+monitoring)
RealWorld-HAR: [RealWorld Human Activity Recognition](https://www.uni-mannheim.de/dws/research/projects/activity-recognition/dataset/dataset-realworld/)

We provided the configurations we used for these datasets in Table 1 of our [paper](https://arxiv.org/abs/2310.20071) for your reference. You can then follow the steps in data_preprocess/MOD/extract_samples.py to partition these datasets.

I hope this helps! Please feel free to reach out if you have any further questions.
