### ISSUE TITLE
How to run FOCAL and other models on our own dataset?

### ISSUE THREAD

**Issue by shahaamirbader** [tomoyoshki/focal#2]
Hi, 

I was wondering how can I run FOCAL and the other models you have provided on my own time series dataset that contain signals related to ECG, EEG of participants?

**Comment by tomoyoshki** [comment]
Hi there,

**Running FOCAL on Other Datasets**

- We store our data in `.pt` files and use index files (e.g., `train_index.txt`, `val_index.txt`, `test_index.txt`) as pointers to these `.pt` files. You can refer to `input_utils/multi_modal_dataset.py` to see how the index files and `.pt` files are loaded.
- To use your own dataset with our code, please preprocess your data into a similar format.
- For time-series signals, we sample the sequences using the `partition_subsequences` function in `input_utils/multi_modal_dataset.py`, based on the suffix of the `.pt` files (e.g., `x_{sequence number}.pt`).
- Each `.pt` file should contain a sample in a dictionary format similar to the following:
    ```python
    {
        "data": {
            "location1": {
                "mod1": Tensor,
                "mod2": Tensor
            } 
        },
        "label": LABEL
    }
    ```
- For reference, please review the processed MOD `.pt` files.

Once your data is prepared, you can:

1. Update the `task_default_task` in `params/params_util.py`.
2. Create a YAML file similar to `data/MOD.yaml`. This YAML file should include all the dataset and model configurations.
    - Key fields to update:
        - `location_names` (currently, we only support one location)
        - `modality_names`
        - `num_segments`
        - `loc_mod_in_freq_channels`
        - `loc_mod_in_time_channels`
        - `loc_mod_in_spectrum_len`
        - `seq_len`
    - You can also check out our [paper](https://arxiv.org/abs/2310.20071) for more details on these configurations.
3. Ensure the model configuration in your YAML file matches the shape of your data.

Then, simply specify the dataset you would like to use in your command line: `python train.py -model=[MODEL] -dataset=TestDataset -learn_framework=FOCAL`.

I hope this helps! Please let me know if you have any other questions.
